name: pub_stats_firebase_functions
publish_to: none

environment:
  sdk: ^3.7.0

resolution: workspace

dependencies:
  firebase_js_interop: ^0.0.9
  pub_stats_core:
    path: ../pub_stats_core
  pub_stats_collector:
    path: ../pub_stats_collector

dev_dependencies:
  rexios_lints: ^11.0.4
