name: _
publish_to: none

environment:
  sdk: ^3.8.0

workspace:
  - functions
  - pub_stats
  - pub_stats_collector
  - pub_stats_core

dependency_overrides:
  pub_api_client:
    git:
      url: https://github.com/Rexios80/pub_api_client
      ref: c0d070b762ec8f17909b102c14e6751d3e559127
