name: pub_stats
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  fast_ui: ^0.0.5
  get_it: ^7.2.0
  logger: ^1.1.0
  intl: ^0.17.0
  get_time_ago: ^1.1.1
  font_awesome_flutter: ^10.0.0-beta
  url_launcher: ^6.0.17
  fl_chart: ^0.41.0
  flutter_svg: ^1.0.0
  pub_api_client: ^2.2.0
  flutter_typeahead: ^3.2.4

  pub_stats_core:
    git:
      url: https://github.com/Rexios80/pub_stats_core
      ref: 85841d05a1d3c068da4766cc15e7437bd55d3552

  # Firebase
  firebase_core: ^1.10.6
  firebase_analytics: ^9.0.4
  firebase_app_check: ^0.0.6+3
  firebase_auth: ^3.3.4
  firebase_database: ^9.0.4
  firebase_performance: ^0.8.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  rexios_lints: ^1.0.0
  flutter_native_splash: ^1.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#000000"
  image: assets/images/logo.png
  android: false
  ios: false
