name: _
publish_to: none

environment:
  sdk: ^3.6.0

workspace:
  - functions
  - pub_stats
  - pub_stats_collector
  - pub_stats_core

dependency_overrides:
  pub_api_client:
    git:
      prs:
        - https://github.com/leoafarias/pub_api_client/pull/59
      url: https://github.com/Rexios80/pub_api_client
      ref: d7b648cadabfd2d10f6c567b619609d82f3d7072
  dart_mappable:
    git:
      prs:
        - https://github.com/schultek/dart_mappable/pull/261
      url: https://github.com/Rexios80/dart_mappable
      ref: 793f740a6774e55226f3ec8bc3bba48badecc79f
      path: packages/dart_mappable
  # dart_mappable:
  #   path: ../dart_mappable/packages/dart_mappable
