name: pub_stats
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  fast_ui: ^0.0.4
  get_it: ^7.2.0
  material_floating_search_bar: ^0.3.6
  logger: ^1.1.0
  pub_stats_core:
    git:
      url: https://github.com/Rexios80/pub_stats_core
      ref: ad79857dd96ebaa7babcb1738dfc02010466f178
  pub_api_client:
    git:
      url: https://github.com/Rexios80/pub_api_client
      ref: 9b994209070472159a4f401fea5d803b2164264b

dev_dependencies:
  flutter_test:
    sdk: flutter

  rexios_lints: ^1.0.0

  # Firebase
  firebase_core: ^1.10.6
  firebase_analytics: ^9.0.4
  firebase_app_check: ^0.0.6+3
  firebase_auth: ^3.3.4
  firebase_database: ^9.0.4
  firebase_performance: ^0.8.0+3

flutter:
  uses-material-design: true
