name: pub_stats
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  fast_ui: ^0.1.0
  get_it: ^7.2.0
  logger: ^1.1.0
  intl: ^0.18.0
  get_time_ago: ^1.1.1
  font_awesome_flutter: ^10.0.0-beta
  url_launcher: ^6.0.17
  fl_chart: ^0.60.0
  flutter_svg: ^2.0.0+1
  pub_api_client: ^2.2.0

  pub_stats_core:
    git:
      url: https://github.com/Rexios80/pub_stats_core
      ref: 7c772c42613a345dfaaef0779622bf9d9a2e9741

  # Firebase
  firebase_core: ^2.4.1
  firebase_analytics: ^10.1.0
  firebase_app_check: ^0.1.1+8
  firebase_auth: ^4.2.2
  firebase_database: ^10.0.9
  firebase_performance: ^0.9.0+10

  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  rexios_lints: ^5.0.0
  flutter_native_splash: ^2.0.1+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#000000"
  image: resources/logo.png
  android: false
  ios: false
