name: pub_stats_core
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  http: ^1.1.0
  json_annotation: ^4.8.1
  pub_api_client: ^3.0.0

dev_dependencies:
  rexios_lints: ^9.1.0
  build_runner: ^2.1.7
  json_serializable: ^6.1.3
  freezed: ^2.4.5

dependency_overrides:
  pub_api_client:
    git:
      prs:
        - https://github.com/leoafarias/pub_api_client/pull/54
        - https://github.com/leoafarias/pub_api_client/pull/55
        - https://github.com/leoafarias/pub_api_client/pull/58
      url: https://github.com/Rexios80/pub_api_client
      ref: 4d881fcc25a35b182e028a58db844b51534b32d8
