name: pub_stats_core
publish_to: none

environment:
  sdk: ^3.7.0

resolution: workspace

dependencies:
  equatable: ^2.0.5
  freezed_annotation: ^3.0.0
  http: ^1.1.0
  json_annotation: ^4.8.1
  pub_api_client: ^3.1.1

dev_dependencies:
  rexios_lints: ^11.0.4
  build_runner: ^2.1.7
  json_serializable: ^6.1.3
  freezed: ^3.0.4
  test: ^1.25.0
