name: pub_stats_core
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  http: ^1.1.0
  json_annotation: ^4.8.1
  pub_api_client: ^2.2.0

dev_dependencies:
  rexios_lints: ^6.0.1
  build_runner: ^2.1.7
  json_serializable: ^6.1.3
  freezed: ^2.4.5
