name: dart_cloud_run_template
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  shelf: ^1.3.2
  shelf_router: ^1.1.3
  shelf_proxy: ^1.0.2
  shelf_cors_headers: ^0.1.3

dev_dependencies:
  rexios_lints: ^6.0.1
  test: ^1.15.7
  test_process: ^2.0.0
  http: ^1.1.0
